# Default Configuration File for DropParty Plugin.
mysql:
  host: "localhost"
  username: "yourdatabaseuser"
  password: "yourdatabasepass"
  database: "database"
  port: 3306
  prefix: "dp_"

#Default settings for a drop party.
defaultpartysettings:
  #Delay between dropping each itemstack in a drop party, in ticks.
  itemdelay: 5
  #Max Drop Party Length, in seconds.
  maxlength: 300
  #Max Stack Size of an item stack being dropped. itemstacks bigger than this will be split up.
  maxstack: 8
  
messages:
#NOTE: %PartyName% will be replaced with the name of the drop party you created/started/modified/etc.
#NOTE: You may use color codes &0-&9, &a-&f, &k-&o, and &r. http://www.minecraftwiki.net/wiki/Formatting_codes
#Prefix. Comes before EVERY drop party message.
  dpprefix: "&8[&bDropParty&8]"
#Command Messages
  dpcreate: "&bDrop Party '%PartyName%' Created Successfully."
  dpdelete: "&bDrop Party '%PartyName%' Deleted Successfully."
  dpstart: "&bStarted Drop Party '%PartyName%'."
  dpstop: "&bStopped Drop Party '%PartyName%'."
  dpsetchest: "&bSet Chest for Drop Party '%PartyName%' Successfully."
  dpsetchestmode: "&bRight Click Chests To Set Them As '%PartyName%' Source Chests. Type /dp chest set %PartyName% Again To Turn Off Selection Mode."
  dpsetchestmodeoff: "&bTurned Off Chest Selection Mode For '%PartyName%'."
  dpsetitempoint: "&bSet ItemPoint for Drop Party '%PartyName%' Successfully."
  dpsetitempointmode: "&bPlace Glowstone To Set Item Points For '%PartyName%'. Type /dp itempoint set %PartyName% Again To Turn Off Selection Mode."
  dpsetitempointmodeoff: "&bTurned Off ItemPoint Selection Mode For '%PartyName%'."
  dpsetteleport: "&bSet Teleport for Drop Party '%PartyName%' Successfully."
  dpsetitemdelay: "&bSet Item Delay for Drop Party '%PartyName%' Successfully."
  dpsetmaxlength: "&bSet Max Length for Drop Party '%PartyName%' Successfully."
  dpsetmaxstack: "&bSet Max Stack Size for Drop Party '%PartyName%' Successfully."
  dpremovechest: "&bRemoved Chest from Drop Party '%PartyName%' Successfully."
  dpremoveitempoint: "&bRemoved ItemPoint from Drop Party '%PartyName%' Successfully."
  dpteleport: "&bTeleported To Drop Party '%PartyName%'."  
#Broadcasts
  dpannouncestart: "&bDrop Party '%PartyName%' Started! Teleport With /dp teleport %PartyName%"
  dpannouncestop: "&bDrop Party '%PartyName%' Has Ended!"
#Errors
  dpcreateerror: "&4Failed To Create Drop Party '%PartyName%'."
  dpdeleteerror: "&4Failed To Delete Drop Party '%PartyName%'."
  dpstarterror: "&4Failed To Start Drop Party '%PartyName%'."
  dpstoperror: "&4Failed To Stop Drop Party '%PartyName%'."
  dpsetchesterror: "&4Failed To Set Chest for Drop Party '%PartyName%'."
  dpsetitempointerror: "&4Failed To Set ItemPoint for Drop Party '%PartyName%'."
  dpsetteleporterror: "&4Failed To Set Teleport for Drop Party '%PartyName%'."
  dpsetitemdelayerror: "&4Failed To Set Item Delay for Drop Party '%PartyName%'."
  dpsetmaxlengtherror: "&4Failed To Set Max Length for Drop Party '%PartyName%'."
  dpsetmaxstackerror: "&4Failed To Set Max Stack Size for Drop Party '%PartyName%'."
  dpremovechesterror: "&4Failed To Remove Chest from Drop Party '%PartyName%'."
  dpremoveitempointerror: "&4Failed To Remove ItemPoint from Drop Party '%PartyName%'."
  dpteleporterror: "&4Failed To Teleport to Drop Party '%PartyName%'."
#Other
  dpchestalreadyexists: "&4There Is Already A Drop Party '%PartyName%' Chest Here."
  dpitempointalreadyexists: "&4There Is Already A Drop Party '%PartyName%' ItemPoint Here."
  dppartydoesntexist: "&4Drop Party '%PartyName%' Does Not Exist."
  dppartyalreadyexists: "&4Drop Party '%PartyName%' Already Exists."
  dppartyoutofitems: "&4Drop Party '%PartyName%' Has Run Out Of Items."
  dpnochestsfound: "&4No Drop Party '%PartyName%' Chests Found."
  dpnoitempointsfound: "&4No Drop Party '%PartyName%' Item Points Found."
  dpargumentserror: "&4Incorrect Amount Of Arguments."
  dpnopermission: "&4You Do Not Have The Permission dropparty.admin"