debug: true
defaultsettings:
  maxlength: 6000
  itemdelay: 5
  maxstacksize: 8
  fireworkamount: 8
  fireworkdelay: 2
  startperiodically: false
  startperiod: 144000
  votetostart: false
  requiredvotes: 50