# Default Configuration File for DropParty Plugin.
mysql:
  host: "localhost"
  username: "yourdatabaseuser"
  password: "yourdatabasepass"
  database: "database"
  port: 3306
  prefix: "dp_"
messages:
#NOTE: %PartyName% will be replaced with the name of the drop party you created/started/modified/etc.
#NOTE: You may use color codes &0-&9, &a-&f, &k-&o, and &r. http://www.minecraftwiki.net/wiki/Formatting_codes
  dpcreate: "&bDrop Party '%PartyName%' Created Successfully."
  dpremove: "&bDrop Party '%PartyName%' Removed Successfully."
  dpstart: "&bStarted Drop Party '%PartyName%'."
  dpstop: "&bStopped Drop Party '%PartyName%'."
  dpannouncestart: "&bDrop Party '%PartyName%' Started! Teleport With /dp teleport %PartyName%"
  dpannouncestop: "&bDrop Party '%PartyName%' Has Ended!"
  dpsetchest: "&bSet Chest for Drop Party '%PartyName%' Successfully."
  dpsetitempoint: "&bSet ItemPoint for Drop Party '%PartyName%' Successfully."
  dpsetteleport: "&bSet Teleport for Drop Party '%PartyName%' Successfully."
  dpsetitemdelay: "&bSet Item Delay for Drop Party '%PartyName%' Successfully."
  dpsetmaxlength: "&bSet Max Length for Drop Party '%PartyName%' Successfully."
  dpsetmaxstack: "&bSet Max Stack Size for Drop Party '%PartyName%' Successfully."
  dpremovechest: "&bRemoved Chest from Drop Party '%PartyName%' Successfully."
  dpremoveitempoint: "&bRemoved ItemPoint from Drop Party '%PartyName%' Successfully."
  dpteleport: "&bTeleported To Drop Party '%PartyName%'."
  dpcreateerror: "&4Failed To Create Drop Party '%PartyName%'."
  dpremoveerror: "&4Failed To Remove Drop Party '%PartyName%'."
  dpstarterror: "&4Failed To Start Drop Party '%PartyName%'."
  dpstoperror: "&4Failed To Stop Drop Party '%PartyName%'."
  dpsetchesterror: "&4Failed To Set Chest for Drop Party '%PartyName%'."
  dpsetitempointerror: "&4Failed To Set ItemPoint for Drop Party '%PartyName%'."
  dpsetteleporterror: "&4Failed To Set Teleport for Drop Party '%PartyName%'."
  dpsetitemdelayerror: "&4Failed To Set Item Delay for Drop Party '%PartyName%'."
  dpsetmaxlengtherror: "&4Failed To Set Max Length for Drop Party '%PartyName%'."
  dpsetmaxstackerror: "&4Failed To Set Max Stack Size for Drop Party '%PartyName%'."
  dpremovechesterror: "&4Failed To Remove Chest from Drop Party '%PartyName%'."
  dpremoveitempointerror: "&4Failed To Remove ItemPoint from Drop Party '%PartyName%'."
  dpteleporterror: "&4Failed To Teleport to Drop Party '%PartyName%'."
  dppartydoesntexist: "&4Drop Party '%PartyName%' Does Not Exist."