name: DropParty
version: 2
description: Create Awesome Drop Parties.
author: ampayne2
main: me.ampayne2.DropParty.DropParty
commands:
  dropparty:
    aliases: dp
    permission: dropparty.admin
permissions:
  dropparty.admin:
    description: Gives access to all Drop Party Admin commands