name: DropParty
version: 0.1
description: Create Simple Drop Parties.
author: ampayne2
main: me.ampayne2.DropParty.DropParty
commands:
  dropparty:
    aliases: dp
    permission: dropparty.admin
    permission-message: You do note have permission for Drop Party.
    usage: "Usage: /[dropparty/dp] [setchest/setitem/start/stop]."
permissions:
  dropparty.admin:
    description: Gives access to all Drop Party commands